version: '3.1'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  jpagent:
    image: oakes1218/jpagent:v1
    restart: always
    ports:
      - 8888:8989
    environment:
      JP_MYSQL_HOST: mysql
      JP_MYSQL_PORT: 3306
      JP_MYSQL_DATABASE: product
      JP_MYSQL_USER: root
      JP_MYSQL_PASSWORD: "password"
      JP_SERVER_PORT: ":8989"
      JP_MYSQL_MAXIDLE: 10
      JP_MYSQL_MAXCONN: 100
      JP_MYSQL_CONNMAXLIFETTIME: 30
      JP_MYSQL_SINGULARTABLE: "true"
      JP_MYSQL_LOGMODE: "true"
    depends_on:
      - db
      - phpmyadmin
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: